abstract class ampas {
    static void bestDir(String Name, int Year) {
        System.out.println("The winner of the Oscar for Outstanding Directing of a Feature Film in " + Year + " was " + Name + "."+ System.lineSeparator());
    }

    public static void main(String[] args) {
        bestDir("Frank Borzage", 1927);
        bestDir("Lewis Milestone", 1928);
        bestDir("Frank Lloyd", 1929);
        bestDir("Lewis Milestone", 1930);
        bestDir("Norman Taurog", 1931);
        bestDir("Frank Borzage", 1932);
        bestDir("Frank Lloyd", 1933);
        bestDir("Frank Capra", 1934);
        bestDir("John Ford", 1935);
        bestDir("Frank Capra", 1936);
        bestDir("Leo McCarey", 1937);
        bestDir("Frank Capra", 1938);
        bestDir("Victor Fleming", 1939);
        bestDir("John Ford", 1940);
        bestDir("John Ford", 1941);
        bestDir("William Wyler", 1942);
        bestDir("Michael Curtiz", 1943);
        bestDir("Leo McCarey", 1944);
        bestDir("Billy Wilder", 1945);
        bestDir("William Wyler", 1946);
        bestDir("Elia Kazan", 1947);
        bestDir("John Huston", 1948);
        bestDir("Joseph L. Mankiewicz", 1949);
        bestDir("Joseph L. Mankiewicz", 1950);
        bestDir("George Stevens", 1951);
        bestDir("John Ford", 1952);
        bestDir("Fred Zinnemann", 1953);
        bestDir("Elia Kazan", 1954);
        bestDir("Delbert Mann", 1955);
        bestDir("George Stevens", 1956);
        bestDir("David Lean", 1957);
        bestDir("Vincente Minnelli", 1958);
        bestDir("William Wyler", 1959);
        bestDir("Billy Wilder", 1960);
        bestDir("Jerome Robbins & Robert Wise", 1961);
        bestDir("David Lean", 1962);
        bestDir("Tony Richardson", 1963);
        bestDir("George Cukor", 1964);
        bestDir("Robert Wise", 1965);
        bestDir("Fred Zinnemann", 1966);
        bestDir("Mike Nichols", 1967);
        bestDir("Carol Reed", 1968);
        bestDir("John Schlesinger", 1969);
        bestDir("Franklin J. Schaffner", 1970);
        bestDir("William Friedkin", 1971);
        bestDir("Bob Fosse", 1972);
        bestDir("George Roy Hill", 1973);
        bestDir("Francis Ford Coppola", 1974);
        bestDir("Milos Forman", 1975);
        bestDir("John G. Avildsen", 1976);
        bestDir("Woody Allen", 1977);
        bestDir("Michael Cimino", 1978);
        bestDir("Robert Benton", 1979);
        bestDir("Robert Redford", 1980);
        bestDir("Warren Beatty", 1981);
        bestDir("Richard Attenborough", 1982);
        bestDir("James L. Brooks", 1983);
        bestDir("Milos Forman", 1984);
        bestDir("Sydney Pollack", 1985);
        bestDir("Oliver Stone", 1986);
        bestDir("Bernardo Bertolucci", 1987);
        bestDir("Barry Levinson", 1988);
        bestDir("Oliver Stone", 1989);
        bestDir("Kevin Costner", 1990);
        bestDir("Jonathan Demme", 1991);
        bestDir("Clint Eastwood", 1992);
        bestDir("Steven Spielberg", 1993);
        bestDir("Robert Zemeckis", 1994);
        bestDir("Mel Gibson", 1995);
        bestDir("Anthony Minghella", 1996);
        bestDir("James Cameron", 1997);
        bestDir("Steven Spielberg", 1998);
        bestDir("Sam Mendes", 1999);
        bestDir("Steven Soderbergh", 2000);
        bestDir("Ron Howard", 2001);
        bestDir("Roman Polanski", 2002);
        bestDir("Peter Jackson", 2003);
        bestDir("Clint Eastwood", 2004);
        bestDir("Ang Lee", 2005);
        bestDir("Martin Scorsese", 2006);
        bestDir("Joel Coen and Ethan Coen", 2007);
        bestDir("Danny Boyle", 2008);
        bestDir("Kathryn Bigelow", 2009);
        bestDir("Tom Hooper", 2010);
        bestDir("Michel Hazanavicius", 2011);
        bestDir("Ang Lee", 2012);
        bestDir("Alfonso Cuarón", 2013);
        bestDir("Alejandro González Iñárritu", 2014);
        bestDir("Alejandro González Iñárritu", 2015);
        bestDir("Damien Chazelle", 2016);
        bestDir("Guillermo del Toro", 2017);
        bestDir("Alfonso Cuarón", 2018);
        bestDir("Bong Joon-ho", 2019);
        bestDir("Chloé Zhao", 2020);
        bestDir("Jane Campion", 2021);
    }
}